### ISSUE TITLE
feature/LoginSignupLogicFeature/

### ISSUE THREAD

**Issue by SecretCandy** [kybaq/3-feet#18]
## To-Do
- [x] 로그인 페이지 기능 구현
- [x] 회원가입 페이지 기능 구현
- [x] 로그인 페이지 유효성 검사
- [x] 회원가입 페이지 유효성 검사
- [x] 회원가입 페이지 중복 검사

**Comment by MinKonKim** [comment]
회원가입 후에 유저 정보 전역에서 받아질 수 있 수 있는지도 고민해야합니다.
