### ISSUE TITLE
fix/InsertPulblicUserTable/

### ISSUE THREAD

**Issue by MinKonKim** [kybaq/3-feet#35]
## To-Do
- [x] user 데이터 저장 확인
- [ ] user 데이터 조회 확인
- [ ]  user 데이터 수정 확인

### 
### ???
