### ISSUE TITLE
fix/supabaseLoginCheck/

### ISSUE THREAD

**Issue by MinKonKim** [kybaq/3-feet#37]
## To-Do
- [ ]  user 데이터 조회 확인
- [ ]  user 데이터 수정 확인
- [ ]  session 에 user정보 잘 들어가는지 확인 및 수정할거 있으면 수정

## ETC
- 
### 
### ???
