### ISSUE TITLE
feature/detail-page

### ISSUE THREAD

**Issue by hyeonseok98** [kybaq/3-feet#41]
## To-Do
- [x] 중첩 모달 로직 수정
- [x] 모달 backdrop 수정
- [x] 비로그인 유저 로그인 화면으로 리다이렉트 기능 구현
- [x] 댓글 삭제 기능 구현

### 2024-06-21
