### ISSUE TITLE
feature/mapUI/

### ISSUE THREAD

**Issue by kybaq** [kybaq/3-feet#5]
## To-Do
- [x] 별도의 Header 구성
- [x] 네이버 지도에 나타나도록 구성
- [x] Collapse 메뉴를 통해 구단 별 홈 구장으로 panning

## ETC
없음

###  2024.06.19
