### ISSUE TITLE
feature/detail/

### ISSUE THREAD

**Issue by hyeonseok98** [kybaq/3-feet#6]
## To-Do
- [x] 모달 컴포넌트 제작
- [x] 제작된 tour-api hook 사용하여 업체 정보 가져오기
- [x] 댓글(글자수 제한 200자)
- [x] 비로그인 유저 댓글 작성 불가

###  미정
