### ISSUE TITLE
feautre/BaseBallDBSetUp/

### ISSUE THREAD

**Issue by MinKonKim** [kybaq/3-feet#9]
## To-Do

- [x]  Club Table 생성 및 데이터 저장
- [x]  DB연결해서 데이터 받아오는지 확인
- [x] Club 데이터들을 전역으로 관리하기

### 

###  2024.06.19
